### PR TITLE
db.syncContinuously is deprecated

### PR DESCRIPTION
**Pull request by poupougnac**

### CODE REVIEW

**Comment by piglovesyou** [comment]
That's true. Thank you.

**Comment by piglovesyou** [comment]
@paldepind Do you have time to do that? Or if you grant me as an npm collaborator I'll take care of it as much as possible.

**Comment by paldepind** [comment]
I've published a new version of syncedd-server to npm.

I'll add you as a npm collaborator @piglovesyou. Is your username on npm identical to here on GitHub?

**Comment by piglovesyou** [comment]
Thank you. Yes it's identical. [This is my profile page](https://www.npmjs.com/~piglovesyou)

**Comment by piglovesyou** [comment]
@paldepind 👋

**Comment by paldepind** [comment]
Sorry :sweat: 

I've added you as a collaborator to all the synceddb-* packages :+1:

**Comment by piglovesyou** [comment]
Thank you, no problem. You are the king of the packages 👑

**Pull request merged**
