### PR TITLE
Refactoring: Split classes into files and etc.

### PR DESCRIPTION
**Pull request by piglovesyou**
This is my suggestion of refactoring synceddb-client. It's all up to your syntax policy so any suggestion would be appreciated.

- Use Array.from
- transform-remove-console for production build
- Use underscore for general functions
- No `this` variable because we have arrow function
- Use rest parameter
- Split into files

### CODE REVIEW

**Comment by paldepind** [comment]
Looks great! Would you like to have commit access to the repository? I am no longer working on it myself and your PRs have been nice.

**Comment by piglovesyou** [comment]
Thanks for reviewing again. And I'm glad to hear that, yes I would like to have one. Maybe I will be fairly active to maintain it as long as my project longs which depends on synceddb.

So let me make sure how often I should ask you advices before making changes.
- Bug fix: maybe this would be ok without your permission
- New API
  - Right now I'm thinking capability to pass `keyPath` option
  - And flexible api to control `cursor`
- Breaking changes
  - to introduce a new functionality
- Deciding milestone
- Project policy
  - to answer questions from developers on issues

And of course any comment AFTER my changes can be discussable among us at any time.

**Comment by paldepind** [comment]
Very late response. I apologize.

I've given you push access to the repository.

I think if you ask in the case where

* In doubt/want my opinion
* Making breaking changes

Besides that you can do what you want :smile:

**Comment by piglovesyou** [comment]
Okey, thanks. I'll send a mention when I need your help.

**Pull request merged**
